# Setup the common environment
- name: Update apt cache
  apt: update_cache=yes
  tags:
    - common

- name: Update OS
  apt: upgrade=dist force=yes
  tags:
    - common

- name: Install python-passlib library
  apt: name=python-passlib state=latest
  tags:
    - common
