# PHP playbook tasks
- name: Install PHP
  apt: name={{ item }} state=latest
  with_items:
  - php5
  - libapache2-mod-php5
  - php5-mcrypt
  register: result

- name: Set index.php as priority
  template: src=dir.conf dest=/etc/apache2/mods-enabled/dir.conf mode=0644
  when: result|success
