- name: Check if nagios core is installed on the server
  command: bash -c "/usr/local/nagios/bin/nagios --version | grep ^Nagios | awk '{print $3}'"
  register: nagios_core_version
  tags:
    - nagios_core

- debug: var=nagios_core_version
  tags:
    - nagios_core

- name: Download and Extract nagios core file
  unarchive: src=https://assets.nagios.com/downloads/nagioscore/releases/{{ nagios }}.tar.gz dest={{ ansible_env.PWD }} copy=no
  when: nagios_core_version.stdout != '4.1.1'
  tags:
    - nagios_core

- name: Run nagios installation in the nagios directory
  command: "{{ item }}"
  when: nagios_core_version.stdout != '4.1.1'
  with_items:
    - ./configure --with-nagios-group=nagios --with-command-group=nagcmd
    - make clean
    - make all
    - make install
    - make install-commandmode
    - make install-init
    - make install-config
    - /usr/bin/install -c -m 644 sample-config/httpd.conf /etc/apache2/sites-available/nagios.conf
  args:
    chdir: "{{ ansible_env.PWD}}/{{ nagios }}"
  tags:
    - nagios_core

- name: Add web server user to nagcmd group
  user: name=www-data groups=nagcmd append=yes
  when: nagios_core_version.stdout != '4.1.1'
  tags:
    - nagios_core